import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Providers } from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: 
Readonly<{children: React.ReactNode;}>) {
  return (
    <SessionProvider>
      <html lang="en" className="dark">
        <body>
          <Providers>
            {children}
          </Providers>
        </body>
      </html>
    </SessionProvider>
  );
}
