import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Providers } from "./providers";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: 
Readonly<{children: React.ReactNode;}>) {
  return (
    <SessionProvider>
      <html lang="hu" className="dark">
        <body>
          <NextTopLoader
            color="hsl(var(--nextui-primary) / var(--nextui-primary-opacity, 1))"
            initialPosition={0.08}
            crawlSpeed={100}
            height={2}
            crawl={true}
            showSpinner={true}
            easing="ease"
            speed={200}
            shadow="0 0 10px #2299DD,0 0 5px #2299DD"
            template='<div class="bar" role="bar"><div class="peg"></div></div> 
            <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
            zIndex={1600}
            showAtBottom={false}
          />
          <Providers>
            {children}
          </Providers>
        </body>
      </html>
    </SessionProvider>
  );
}
